// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createAthlete = `-- name: CreateAthlete :execresult
INSERT INTO athletes (name, grade, personal_record, events)
VALUES (?, ?, ?, ?)
`

type CreateAthleteParams struct {
	Name           string
	Grade          int32
	PersonalRecord sql.NullString
	Events         sql.NullString
}

func (q *Queries) CreateAthlete(ctx context.Context, arg CreateAthleteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAthlete,
		arg.Name,
		arg.Grade,
		arg.PersonalRecord,
		arg.Events,
	)
}

const createMeet = `-- name: CreateMeet :execresult
INSERT INTO meets (name, date, location, description)
VALUES (?, ?, ?, ?)
`

type CreateMeetParams struct {
	Name        string
	Date        time.Time
	Location    string
	Description sql.NullString
}

func (q *Queries) CreateMeet(ctx context.Context, arg CreateMeetParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMeet,
		arg.Name,
		arg.Date,
		arg.Location,
		arg.Description,
	)
}

const createResult = `-- name: CreateResult :execresult
INSERT INTO results (athlete_id, meet_id, time, place)
VALUES (?, ?, ?, ?)
`

type CreateResultParams struct {
	AthleteID int32
	MeetID    int32
	Time      string
	Place     int32
}

func (q *Queries) CreateResult(ctx context.Context, arg CreateResultParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createResult,
		arg.AthleteID,
		arg.MeetID,
		arg.Time,
		arg.Place,
	)
}

const deleteAthlete = `-- name: DeleteAthlete :exec
DELETE FROM athletes WHERE id = ?
`

func (q *Queries) DeleteAthlete(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAthlete, id)
	return err
}

const deleteMeet = `-- name: DeleteMeet :exec
DELETE FROM meets WHERE id = ?
`

func (q *Queries) DeleteMeet(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMeet, id)
	return err
}

const deleteResult = `-- name: DeleteResult :exec
DELETE FROM results WHERE id = ?
`

func (q *Queries) DeleteResult(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteResult, id)
	return err
}

const getAllAthletes = `-- name: GetAllAthletes :many
SELECT id, name, grade, personal_record, events, created_at
FROM athletes
ORDER BY name
`

func (q *Queries) GetAllAthletes(ctx context.Context) ([]Athlete, error) {
	rows, err := q.db.QueryContext(ctx, getAllAthletes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Athlete
	for rows.Next() {
		var i Athlete
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Grade,
			&i.PersonalRecord,
			&i.Events,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMeets = `-- name: GetAllMeets :many
SELECT id, name, date, location, description, created_at
FROM meets
ORDER BY date
`

func (q *Queries) GetAllMeets(ctx context.Context) ([]Meet, error) {
	rows, err := q.db.QueryContext(ctx, getAllMeets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meet
	for rows.Next() {
		var i Meet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.Location,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAthleteByID = `-- name: GetAthleteByID :one
SELECT id, name, grade, personal_record, events, created_at
FROM athletes
WHERE id = ?
`

func (q *Queries) GetAthleteByID(ctx context.Context, id int32) (Athlete, error) {
	row := q.db.QueryRowContext(ctx, getAthleteByID, id)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Grade,
		&i.PersonalRecord,
		&i.Events,
		&i.CreatedAt,
	)
	return i, err
}

const getMeetResults = `-- name: GetMeetResults :many
SELECT r.id, r.time, r.place, a.id AS athlete_id, a.name AS athlete_name, a.grade AS athlete_grade
FROM results r
JOIN athletes a ON r.athlete_id = a.id
WHERE r.meet_id = ?
ORDER BY r.place
`

type GetMeetResultsRow struct {
	ID           int32
	Time         string
	Place        int32
	AthleteID    int32
	AthleteName  string
	AthleteGrade int32
}

func (q *Queries) GetMeetResults(ctx context.Context, meetID int32) ([]GetMeetResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMeetResults, meetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMeetResultsRow
	for rows.Next() {
		var i GetMeetResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.Time,
			&i.Place,
			&i.AthleteID,
			&i.AthleteName,
			&i.AthleteGrade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResultsByMeetID = `-- name: GetResultsByMeetID :many
SELECT r.id, r.athlete_id, r.meet_id, r.time, r.place, r.created_at
FROM results r
WHERE r.meet_id = ?
ORDER BY r.place
`

func (q *Queries) GetResultsByMeetID(ctx context.Context, meetID int32) ([]Result, error) {
	rows, err := q.db.QueryContext(ctx, getResultsByMeetID, meetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Result
	for rows.Next() {
		var i Result
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.MeetID,
			&i.Time,
			&i.Place,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopTimes = `-- name: GetTopTimes :many
SELECT r.id, r.time, r.place, a.id AS athlete_id, a.name AS athlete_name, m.id AS meet_id, m.name AS meet_name, m.date AS meet_date
FROM results r
JOIN athletes a ON r.athlete_id = a.id
JOIN meets m ON r.meet_id = m.id
ORDER BY r.time ASC
LIMIT 10
`

type GetTopTimesRow struct {
	ID          int32
	Time        string
	Place       int32
	AthleteID   int32
	AthleteName string
	MeetID      int32
	MeetName    string
	MeetDate    time.Time
}

func (q *Queries) GetTopTimes(ctx context.Context) ([]GetTopTimesRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopTimes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopTimesRow
	for rows.Next() {
		var i GetTopTimesRow
		if err := rows.Scan(
			&i.ID,
			&i.Time,
			&i.Place,
			&i.AthleteID,
			&i.AthleteName,
			&i.MeetID,
			&i.MeetName,
			&i.MeetDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAthlete = `-- name: UpdateAthlete :exec
UPDATE athletes
SET name = ?, grade = ?, personal_record = ?, events = ?
WHERE id = ?
`

type UpdateAthleteParams struct {
	Name           string
	Grade          int32
	PersonalRecord sql.NullString
	Events         sql.NullString
	ID             int32
}

func (q *Queries) UpdateAthlete(ctx context.Context, arg UpdateAthleteParams) error {
	_, err := q.db.ExecContext(ctx, updateAthlete,
		arg.Name,
		arg.Grade,
		arg.PersonalRecord,
		arg.Events,
		arg.ID,
	)
	return err
}

const updateMeet = `-- name: UpdateMeet :exec
UPDATE meets
SET name = ?, date = ?, location = ?, description = ?
WHERE id = ?
`

type UpdateMeetParams struct {
	Name        string
	Date        time.Time
	Location    string
	Description sql.NullString
	ID          int32
}

func (q *Queries) UpdateMeet(ctx context.Context, arg UpdateMeetParams) error {
	_, err := q.db.ExecContext(ctx, updateMeet,
		arg.Name,
		arg.Date,
		arg.Location,
		arg.Description,
		arg.ID,
	)
	return err
}

const updateResult = `-- name: UpdateResult :exec
UPDATE results
SET athlete_id = ?, meet_id = ?, time = ?, place = ?
WHERE id = ?
`

type UpdateResultParams struct {
	AthleteID int32
	MeetID    int32
	Time      string
	Place     int32
	ID        int32
}

func (q *Queries) UpdateResult(ctx context.Context, arg UpdateResultParams) error {
	_, err := q.db.ExecContext(ctx, updateResult,
		arg.AthleteID,
		arg.MeetID,
		arg.Time,
		arg.Place,
		arg.ID,
	)
	return err
}
